
package com.troy.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoteSubmitActivityService", targetNamespace = "http://ws.troy.com/", wsdlLocation = "http://localhost:7001/AcsActivity/RemoteSubmitActivityService?WSDL")
public class RemoteSubmitActivityService
    extends Service
{

    private final static URL REMOTESUBMITACTIVITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTESUBMITACTIVITYSERVICE_EXCEPTION;
    private final static QName REMOTESUBMITACTIVITYSERVICE_QNAME = new QName("http://ws.troy.com/", "RemoteSubmitActivityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/AcsActivity/RemoteSubmitActivityService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTESUBMITACTIVITYSERVICE_WSDL_LOCATION = url;
        REMOTESUBMITACTIVITYSERVICE_EXCEPTION = e;
    }

    public RemoteSubmitActivityService() {
        super(__getWsdlLocation(), REMOTESUBMITACTIVITYSERVICE_QNAME);
    }

    public RemoteSubmitActivityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTESUBMITACTIVITYSERVICE_QNAME, features);
    }

    public RemoteSubmitActivityService(URL wsdlLocation) {
        super(wsdlLocation, REMOTESUBMITACTIVITYSERVICE_QNAME);
    }

    public RemoteSubmitActivityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTESUBMITACTIVITYSERVICE_QNAME, features);
    }

    public RemoteSubmitActivityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteSubmitActivityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemoteSubmitActivity
     */
    @WebEndpoint(name = "RemoteSubmitActivityPort")
    public RemoteSubmitActivity getRemoteSubmitActivityPort() {
        return super.getPort(new QName("http://ws.troy.com/", "RemoteSubmitActivityPort"), RemoteSubmitActivity.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoteSubmitActivity
     */
    @WebEndpoint(name = "RemoteSubmitActivityPort")
    public RemoteSubmitActivity getRemoteSubmitActivityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.troy.com/", "RemoteSubmitActivityPort"), RemoteSubmitActivity.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTESUBMITACTIVITYSERVICE_EXCEPTION!= null) {
            throw REMOTESUBMITACTIVITYSERVICE_EXCEPTION;
        }
        return REMOTESUBMITACTIVITYSERVICE_WSDL_LOCATION;
    }

}
