
package com.troy.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RemoteSubmitActivity", targetNamespace = "http://ws.troy.com/")

public interface RemoteSubmitActivity {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitActivity", targetNamespace = "http://ws.troy.com/", className = "com.troy.ws.SubmitActivity")
    @ResponseWrapper(localName = "submitActivityResponse", targetNamespace = "http://ws.troy.com/", className = "com.troy.ws.SubmitActivityResponse")
    @Action(input = "http://ws.troy.com/RemoteSubmitActivity/submitActivityRequest", output = "http://ws.troy.com/RemoteSubmitActivity/submitActivityResponse")
    public int submitActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
